<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-GU9UD6HI" failures="2" tests="2" name="Error Validation" time="12.355" errors="0" timestamp="2024-01-12T13:32:22 IST">
  <testcase classname="rahulshettyacademy.TESTS.ErrorValidation" name="LoginErrorValidation" time="0.787">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully] but found [Incorrect email or password]">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Incorrect email or password]
at rahulshettyacademy.TESTS.ErrorValidation.LoginErrorValidation(ErrorValidation.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="rahulshettyacademy.TESTS.ErrorValidation" name="ProductErrorValidation" time="2.185">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at rahulshettyacademy.TESTS.ErrorValidation.ProductErrorValidation(ErrorValidation.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Error Validation -->
